### ISSUE TITLE
gevent 更新后再次不兼容

### ISSUE THREAD

**Issue by ls-wen** [zaunist/CTFD-single#1]
可以简单说说解决办法吗？
gevent更新后依旧是不成

**Comment by zaunist** [comment]
能贴一下错误信息吗？当初我遇到的问题，一个是不兼容，还有一个是需要设置DNS服务器。如果是要解决兼容问题，可以去[pypi](https://pypi.org/)查看一下支持的Python版本。

**Comment by ls-wen** [comment]
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eow_ezyc/greenlet_36e6ff6f335a49fa939470a5b2d06710/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eow_ezyc/greenlet_36e6ff6f335a49fa939470a5b2d06710/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-upp6cjce/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/greenlet Check the logs for full command output.

**Comment by ls-wen** [comment]
错误信息如上，谢谢师傅啊

**Comment by ls-wen** [comment]
报错原因是因为gevent 安装greenlet 安装不上。
Running setup.py install for greenlet: finished with status 'error'
请教如何避免，换源已经尝试过了，加版本号删版本号都不成

**Comment by zaunist** [comment]
我刚才构建了一下，也出错了，报错信息在下面，你注意看一下你的报错里有没有这个。
```
 gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
```
我在网上搜了一下，有说是gcc和g++版本不对应导致的

**Comment by zaunist** [comment]
好了，我把g++加上，现在应该能跑了
![image](https://user-images.githubusercontent.com/38528079/113891630-d0290e80-97f7-11eb-9e6e-514721d8c960.png)

**Comment by zaunist** [comment]
done
